-- 修复 company_settings id 列为自增序列
-- Run this in Neon Console SQL Editor

-- 1. 创建序列（如果不存在）
CREATE SEQUENCE IF NOT EXISTS company_settings_id_seq;

-- 2. 修改 id 列使其使用该序列作为默认值
ALTER TABLE "company_settings" ALTER COLUMN "id" SET DEFAULT nextval('company_settings_id_seq');

-- 3. （可选）如果你之前有数据，同步序列值到最大ID
SELECT setval('company_settings_id_seq', COALESCE((SELECT MAX(id) FROM "company_settings"), 0) + 1, false);

-- 或者，如果你的 ID 列定义是普通的 integer 并没有设置 NOT NULL 或 DEFAULT，上面的 ALTER 会修复它。
-- 但如果它是 GENERATED BY DEFAULT AS IDENTITY，可能需要不同的命令。
-- 最通用的修复方式是使用 serial 类型重定义（但 PG 不直接支持改类型为 serial，只能如上设置默认值）。
